### ISSUE TITLE
MOW fails to check if pawns can reach food carriers

### ISSUE THREAD

**Issue by lilwhitemouse** [alextd/RimWorld-MealsOnWheels#1]
Meals On Wheels can make a pawn start a v high number of jobs in as many ticks:

If pawn F is carrying all the food on the map, and pawn H is hungry, pawn H will walk to pawn F and take some food.

However, if pawn F is standing in an area that H is restricted from, F cannot actually attempt that walk, and the job will fail.  However, F is still hungry, so will try again.  Repeat.

I suspect the find-best-food routine isn't checking whether the carrier pawn is in-bounds, so initializes the pawn dropping food...which cannot be reached, so the next food in the carrier's inventory is the best food, which gets dropped, which cannot be..etc.

This came up because I made forbidden zones around an enemy turret I wanted to capture to keep my pawns away from it.

I am very glad my pawns don't have to worry (much) about who is carrying the food!  Thanks!

**Comment by alextd** [comment]
Heyyy, yup, fixed in 1.0.2
